# Autogenerated file
def render(ssids, err):
    yield """
<!doctype html>
<html>

    <head>
        <title>SCEGLI IL WIFI</title>
    </head>

    <body align=\"center\">
        <form method=\"POST\" action=\"/\">
            """
    if ssids:
        yield """
                <p><b>Scegli un wifi:</b></p>
                <select name=\"ssid\">
                """
        for ssid in ssids:
            yield """
                    <option value=\""""
            yield str(ssid)
            yield """\">"""
            yield str(ssid)
            yield """</option>        
                """
        yield """
                </select>
                <br>
                <span>Password: <input type=\"password\" name=\"psw\"/></span><br>
                <span><input type=\"checkbox\" name=\"saveWifi\" value=\"true\" checked> mantenere salvata la configurazione</span><br>
                <input type=\"submit\" content=\"CONNETTI\">
            """
    else:
        yield """
                <h1>No network found!!</h1>
            """
    yield """
        </form>
        <br>
        """
    if err:
        yield """
            <span>"""
        yield str(err)
        yield """</span>
        """
    yield """

    </body>

</html>"""
